[[jcache-component]]
== JCache Component

////
*Available as of Camel version 2.17*
////
*Camel 2.17 より利用可能*


////
The jcache component enables you to perform caching operations using JSR107/JCache as cache implementation.
////

jcache コンポーネントは JSR107/JCache をキャッシュの実装としてキャッシュを利用できるようにする。

////
### URI Format
////
### URI 書式

[source,java]
----------------------------
jcache:cacheName[?options]
----------------------------

////
### URI Options
////
### URI オプション


// endpoint options: START
////
The JCache endpoint is configured using URI syntax:
////
JCache エンドポイントは URI 書式を使って設定される。

----
jcache:cacheName
----

////
with the following path and query parameters:
////
次のパスおよびクエリパラメータで設定される。

////
==== Path Parameters (1 parameters):
////
==== パス パラメータ (1 個):


////
[width="100%",cols="2,5,^1,2",options="header"]
|===
| Name | Description | Default | Type
| *cacheName* | *Required* The name of the cache |  | String
|===
////
[width="100%",cols="2,5,^1,2",options="header"]
|===
| 名前 | 説明 | デフォルト値 | 型
| *cacheName* | *必須* キャッシュ名 |  | String
|===



////
==== Query Parameters (22 parameters):
////
==== クエリパラメータ (22 個):


////
[width="100%",cols="2,5,^1,2",options="header"]
|===
| Name | Description | Default | Type
| *cacheConfiguration* (common) | A Configuration for the Cache |  | Configuration
| *cacheConfigurationProperties* (common) | The Properties for the javax.cache.spi.CachingProvider to create the CacheManager |  | Properties
| *cachingProvider* (common) | The fully qualified class name of the javax.cache.spi.CachingProvider |  | String
| *configurationUri* (common) | An implementation specific URI for the CacheManager |  | String
| *managementEnabled* (common) | Whether management gathering is enabled | false | boolean
| *readThrough* (common) | If read-through caching should be used | false | boolean
| *statisticsEnabled* (common) | Whether statistics gathering is enabled | false | boolean
| *storeByValue* (common) | If cache should use store-by-value or store-by-reference semantics | true | boolean
| *writeThrough* (common) | If write-through caching should be used | false | boolean
| *bridgeErrorHandler* (consumer) | Allows for bridging the consumer to the Camel routing Error Handler, which mean any exceptions occurred while the consumer is trying to pickup incoming messages, or the likes, will now be processed as a message and handled by the routing Error Handler. By default the consumer will use the org.apache.camel.spi.ExceptionHandler to deal with exceptions, that will be logged at WARN or ERROR level and ignored. | false | boolean
| *filteredEvents* (consumer) | Events a consumer should filter. If using filteredEvents option, then eventFilters one will be ignored |  | List
| *oldValueRequired* (consumer) | if the old value is required for events | false | boolean
| *synchronous* (consumer) | if the event listener should block the thread causing the event | false | boolean
| *eventFilters* (consumer) | The CacheEntryEventFilter. If using eventFilters option, then filteredEvents one will be ignored |  | List
| *exceptionHandler* (consumer) | To let the consumer use a custom ExceptionHandler. Notice if the option bridgeErrorHandler is enabled then this option is not in use. By default the consumer will deal with exceptions, that will be logged at WARN or ERROR level and ignored. |  | ExceptionHandler
| *exchangePattern* (consumer) | Sets the exchange pattern when the consumer creates an exchange. |  | ExchangePattern
| *action* (producer) | To configure using a cache operation by default. If an operation in the message header, then the operation from the header takes precedence. |  | String
| *cacheLoaderFactory* (advanced) | The CacheLoader factory |  | Factory
| *cacheWriterFactory* (advanced) | The CacheWriter factory |  | Factory
| *createCacheIfNotExists* (advanced) | Configure if a cache need to be created if it does exist or can't be pre-configured. | true | boolean
| *expiryPolicyFactory* (advanced) | The ExpiryPolicy factory |  | Factory
| *lookupProviders* (advanced) | Configure if a camel-cache should try to find implementations of jcache api in runtimes like OSGi. | false | boolean
|===
////
[width="100%",cols="2,5,^1,2",options="header"]
|===
| 名前 | 説明 | デフォルト値 | 型
| *cacheConfiguration* (共通) | キャッシュの設定。 |  | Configuration
| *cacheConfigurationProperties* (共通) | キャッシュマネージャを作成するための the javax.cache.spi.CachingProvider のプロパティ |  | Properties
| *cachingProvider* (共通) | javax.cache.spi.CachingProvider の完全修飾クラス名。 |  | String
| *configurationUri* (共通) | キャッシュマネージャの実装に対する URI を指定する。 |  | String
| *managementEnabled* (共通) | 管理情報の収集を有効化するか否かを指定する。 | false | boolean
| *readThrough* (共通) | read-through が使用されるか否かを指定する。 | false | boolean
| *statisticsEnabled* (共通) | 統計情報を収集するか否かを指定する。 | false | boolean
| *storeByValue* (共通) | キャッシュが store-by-value もしくは store-by-reference を使用するかを指定する。 | true | boolean
| *writeThrough* (共通) | write-through が使用されるか否かを指定する。 | false | boolean
| *bridgeErrorHandler* (コンシューマ) | コンシューマから Camel エラーハンドラへ橋渡しすることを許可する。コンシューマが入力のメッセージを扱っている際に発生する、どのような例外もエラーハンドラによってメッセージとして処理されることを意味する。デフォルトではコンシューマは例外を扱うために org.apache.camel.spi.ExceptionHandler を使用し、 WARN か ERROR でログに残り無視される。 | false | boolean
| *filteredEvents* (コンシューマ) | コンシューマがフィルタするイベント。filteredEvents オプションを使用する場合は、eventFilters は無視される。 |  | List
| *oldValueRequired* (コンシューマ) | イベントのために古い値が必要か否かを指定する。 | false | boolean
| *synchronous* (コンシューマ) | イベントリスナがイベントを発生させているスレッドをブロックすべきか否かを指定する。 | false | boolean
| *eventFilters* (コンシューマ) | CacheEntryEventFilter。eventFilters オプションを使用している場合、filteredEvents は無視される。 |  | List
| *exceptionHandler* (コンシューマ) | コンシューマがカスタムの ExceptionHandler を使用できるようにする。bridgeErrorHandler のオプションが有効になっている場合は、本オプションは使用されないので注意すること。デフォルトではコンシューマは例外を処理し WARN もしくは ERROR レベルでログが出力されて無視される。 |  | ExceptionHandler
| *exchangePattern* (コンシューマ) | コンシューマが Exchange を生成するときに Exchange パターンをセットする。 |  | ExchangePattern
| *action* (プロデューサ) | デフォルトのキャッシュオペレーションを用いて設定を行う メッセージヘッダ内にオペレーションがある場合は、ヘッダからのオペレーションに優先権がある。 |  | String
| *cacheLoaderFactory* (上級者向け) | CacheLoader ファクトリ。 |  | Factory
| *cacheWriterFactory* (上級者向け) | CacheWriter ファクトリ。 |  | Factory
| *createCacheIfNotExists* (上級者向け) | 存在している、もしくは事前に設定されない場合にキャッシュが生成されるか否かを指定する。 | true | boolean
| *expiryPolicyFactory* (上級者向け) | 有効期限ポリシーのファクトリ factory |  | Factory
| *lookupProviders* (上級者向け) | OSGi のように camel-cache が jcache の実装を検索するように設定するか否かを指定する。 | false | boolean
|===

// endpoint options: END
// spring-boot-auto-configure options: START
////
=== Spring Boot Auto-Configuration
////
=== Spring Boot Auto-Configuration

////
When using Spring Boot make sure to use the following Maven dependency to have support for auto configuration:
////
Spring Boot を使用する場合は、自動設定を有効にするために、次の Maven 依存性を使用する:

////
[source,xml]
----
<dependency>
  <groupId>org.apache.camel</groupId>
  <artifactId>camel-jcache-starter</artifactId>
  <version>x.x.x</version>
  <!-- use the same version as your Camel core version -->
</dependency>
----
////
[source,xml]
----
<dependency>
  <groupId>org.apache.camel</groupId>
  <artifactId>camel-jcache-starter</artifactId>
  <version>x.x.x</version>
  <!-- Camel コアバージョンと同じバージョンを使うこと。 -->
</dependency>
----

////
The component supports 6 options, which are listed below.
////
コンポーネントは以下のリストにある 6 つのオプションをサポートしている。


////
[width="100%",cols="2,5,^1,2",options="header"]
|===
| Name | Description | Default | Type
| *camel.component.jcache.cache-configuration* | A Configuration for the Cache. The option is a javax.cache.configuration.Configuration type. |  | String
| *camel.component.jcache.cache-configuration-properties* | The Properties for the javax.cache.spi.CachingProvider to create the CacheManager. The option is a java.util.Properties type. |  | String
| *camel.component.jcache.caching-provider* | The fully qualified class name of the javax.cache.spi.CachingProvider |  | String
| *camel.component.jcache.configuration-uri* | An implementation specific URI for the CacheManager |  | String
| *camel.component.jcache.enabled* | Enable jcache component | true | Boolean
| *camel.component.jcache.resolve-property-placeholders* | Whether the component should resolve property placeholders on itself when starting. Only properties which are of String type can use property placeholders. | true | Boolean
|===
////
[width="100%",cols="2,5,^1,2",options="header"]
|===
| 名前 | 説明 | デフォルト値 | 型
| *camel.component.jcache.cache-configuration* | キャッシュの設定。 javax.cache.configuration.Configuration 型である。 |  | String
| *camel.component.jcache.cache-configuration-properties* | キャッシュマネージャを生成するための javax.cache.spi.CachingProvider のプロパティ。オプションは java.util.Properties 型である。 |  | String
| *camel.component.jcache.caching-provider* |  javax.cache.spi.CachingProvider の完全修飾クラス名。 |  | String
| *camel.component.jcache.configuration-uri* | キャッシュマネージャの実装に対する URI |  | String
| *camel.component.jcache.enabled* | jcache コンポーネントを有効化する。 | true | Boolean
| *camel.component.jcache.resolve-property-placeholders* | 開始時にコンポーネントが自身でプロパティプレースホルダを解決すべきか否かを指定する。String 型のプロパティのみがプロパティプレースホルダを使用できる。 | true | Boolean
|===

// spring-boot-auto-configure options: END









// component options: START
////
The JCache component supports 5 options, which are listed below.
////
JCache コンポーネントは以下のリストにある 5 つのオプションをサポートしている。


////
[width="100%",cols="2,5,^1,2",options="header"]
|===
| Name | Description | Default | Type
| *cachingProvider* (common) | The fully qualified class name of the javax.cache.spi.CachingProvider |  | String
| *cacheConfiguration* (common) | A Configuration for the Cache |  | Configuration
| *cacheConfiguration Properties* (common) | The Properties for the javax.cache.spi.CachingProvider to create the CacheManager |  | Properties
| *configurationUri* (common) | An implementation specific URI for the CacheManager |  | String
| *resolveProperty Placeholders* (advanced) | Whether the component should resolve property placeholders on itself when starting. Only properties which are of String type can use property placeholders. | true | boolean
|===
////
[width="100%",cols="2,5,^1,2",options="header"]
|===
| 名前 | 説明 | デフォルト値 | 型
| *cachingProvider* (共通) | javax.cache.spi.CachingProvider の完全修飾クラス名 |  | String
| *cacheConfiguration* (共通) | キャッシュの設定 |  | Configuration
| *cacheConfiguration Properties* (共通) | キャッシュマネージャを生成するための javax.cache.spi.CachingProvider のプロパティ。 |  | Properties
| *configurationUri* (共通) | キャッシュマネージャの実装に対する URI |  | String
| *resolveProperty Placeholders* (上級者向け) | 開始時にコンポーネントが自身でプロパティプレースホルダを解決すべきか否かを指定する。String 型のプロパティのみがプロパティプレースホルダを使用できる。 | true | boolean
|===

// component options: END

////
== JCache Policy
////
== JCache ポリシー


////
The JCachePolicy is an interceptor around a route that caches the "result of the route" - the message body - after the route is completed.
  If next time the route is called with a "similar" Exchange, the cached value is used on the Exchange instead of executing the route.
  The policy uses the JSR107/JCache API of a cache implementation, so it's required to add one (e.g. Hazelcast, Ehcache) to the classpath.
////
JCachePolicy は、ルートが完了した後の "ルートの結果" であるメッセージボディをキャッシュする、ルートにまつわるインタセプターである。
次に "類似した" Exchange でルートが呼ばれた場合に、ルートを実行する代わりにキャッシュされた Exchange の値が使用される。
ポリシーはキャッシュ実装に JSR107/JCache API を使用する。そのためクラスパスに（たとえば Hazelcast や Ehcacheを）1 つ追加する必要がある。

////
The policy takes a _key_ value from the received Exchange to get or store values in the cache. By default the _key_ is the message body.
  For example if the route - having a JCachePolicy - receives an Exchange with a String body "fruit" and the body at the
  end of the route is "apple", it stores a _key/value_ pair "fruit=apple" in the cache. If next time another Exchange arrives
  with a body "fruit", the value "apple" is taken from the cache instead of letting the route process the Exchange.
////
ポリシーはキャッシュの値を取得したり値を保存するために、受け取った Exchange から _key_ 値を取得する。デフォルトで _key_ はメッセージボディである。
たとえば、JCachePolicy を保持しているルートが "fruit" の文字列を持つ Exchange を受け取り、ルートの最後でボディが "apple" である場合に、
キャッシュ内で _key/value_ のペアは "fruit=apple" となる。次にボディが "fruit" であるような Exchange が来た場合に、
Exchange を処理するルートを起動する代わりに "apple" がキャッシュから取り出される。


////
So by default the message body at the beginning of the route is the cache _key_ and the body at the end is the stored _value_.
  It's possible to use something else as _key_ by setting a Camel Expression via _.setKeyExpression()_
  that will be used to determine the key.
////
よって、デフォルトでルートの最初におけるメッセージボディがキャッシュの _key_ でルートの最後のメッセージボディが保存される _value_ になる。
キーを決定する _.setKeyExpression()_ を使って Camel Expression を設定することにより _key_ として他のものを使用できる。


////
The policy needs a JCache Cache. It can be set directly by _.setCache()_ or the policy will try to get or create the Cache
  based on the other parameters set.
////
ポリシーは JCache のキャッシュが必要である。_.setCache()_ で直接設定するか、ポリシーが他に設定されているパラメータを元にキャッシュを取得もしくは生成する。


////
Similar caching solution is available for example in Spring using the @Cacheable annotation.
////
たとえば、Spring における @Cacheable アノテーションといった似たようなキャッシュのソリューションが利用可能である。


////
=== JCachePolicy Fields
////
=== JCachePolicy フィールド


////
[width="100%",cols="2,5,3,2",options="header"]
|===
| Name | Description | Default | Type
| *cache* | The Cache to use to store the cached values. If this value is set, _cacheManager_, _cacheName_ and _cacheConfiguration_ is ignored. |  | Cache
| *cacheManager* | The CacheManager to use to lookup or create the Cache. Used only if _cache_ is not set. | Try to find a CacheManager in CamelContext registry or calls the standard JCache _Caching.getCachingProvider().getCacheManager()_. | CacheManager
| *cacheName* | Name of the cache. Get the Cache from cacheManager or create a new one if it doesn't exist. | RouteId of the route. | String
| *cacheConfiguration* | JCache cache configuration to use if a new Cache is created | Default new _MutableConfiguration_ object. | CacheConfiguration
| *keyExpression* | An Expression to evaluate to determine the cache key. | Exchange body | Expression
| *enabled* | If policy is not enabled, no wrapper processor is added to the route. It has impact only during startup, not during runtime. For example it can be used to disable caching from properties. | true | boolean
|===
////
[width="100%",cols="2,5,3,2",options="header"]
|===
| 名前 | 説明 | デフォルト値 | 型
| *cache* | キャッシュされた値を保存するために使用するキャッシュ。この値が設定されると _cacheManager_、 _cacheName_ と _cacheConfiguration_ は無視される。 |  | Cache
| *cacheManager* | キャッシュを調べたり生成したりするために使用するキャッシュマネージャ。 _cache_ が設定されていないときのみ使用される。 | CamelContext レジストリ内でキャッシュマネージャを見つけようとするか、標準の JCache _Caching.getCachingProvider().getCacheManager()_ を呼び出す。 | CacheManager
| *cacheName* | キャッシュの名前。キャッシュマネージャからキャッシュを取得するか、存在しない場合は新規に生成する。 | ルートのルート ID | String
| *cacheConfiguration* | 新規にキャッシュが生成された場合の JCache の設定 | デフォルトで new された _MutableConfiguration_ オブジェクト | CacheConfiguration
| *keyExpression* | キャッシュキーを決定するために評価する Expression。 | Exchange ボディ | Expression
| *enabled* | ポリシーが有効でない場合に、ラップするプロセッサはルートには追加されない。これは起動時のみインパクトを与え、起動中にはインパクトはない。たとえば、プロパティからキャッシュを無効化するために使用される。 | true | boolean
|===


////
## How to determine cache to use?
////
## 使用すべきキャッシュの決め方



////
### Set cache
////
### キャッシュをセットする

////
The cache used by the policy can be set directly. This means you have to configure the cache yourself and get a JCache Cache object,
 but this gives the most flexibility. For example it can be setup in the config xml of the cache provider (Hazelcast, EhCache, ...)
 and used here. Or it's possible to use the standard Caching API as below:
////
ポリシーにより使用されるキャッシュは直接設定できる。これは自分でキャッシュを設定し、JCache のキャッシュオブジェクトを取得しなければいけないことを意味する。しかし、この方法が一番柔軟性がある。
たとえば（Hazelcast や EhCache といった）キャッシュプロバイダの設定 XML 内で設定できる。もしくは以下のような標準キャッシュ API を用いることも可能である。


[source,java]
----------------------------
MutableConfiguration configuration = new MutableConfiguration<>();
configuration.setTypes(String.class, Object.class);
configuration.setExpiryPolicyFactory(CreatedExpiryPolicy.factoryOf(new Duration(TimeUnit.MINUTES, 60)));
CacheManager cacheManager = Caching.getCachingProvider().getCacheManager();
Cache cache = cacheManager.createCache("orders",configuration);

JCachePolicy jcachePolicy = new JCachePolicy();
jcachePolicy.setCache(cache);

from("direct:get-orders")
    .policy(jcachePolicy)
    .log("Getting order with id: ${body}")
    .bean(OrderService.class,"findOrderById(${body})");
----------------------------

////
### Set cacheManager
////
### キャッシュマネージャをセットする

////
If the _cache_ is not set, the policy will try to lookup or create the cache automatically.
 If the _cacheManager_ is set on the policy, it will try to get cache with the set _cacheName_ (routeId by default) from the CacheManager.
 Is the cache does not exist it will create a new one using the _cacheConfiguration_ (new MutableConfiguration by default).
////
_cache_ が設定されていない場合に、ポリシーは自動的にキャッシュを調べたり生成したりする。
もし、ポリシーで _cacheManager_ が設定されている場合に、CacheManager から _cacheName_ （デフォルトでルート ID）を設定したキャッシュを取得しようとする。
キャッシュが存在していない場合は、_cacheConfiguration_ を使用して（デフォルトで MutableConfiguration を new して）新規に作成する。


[source,java]
----------------------------
//In a Spring environment for example the CacheManager may already exist as a bean
@Autowire
CacheManager cacheManager;
...

//Cache "items" is used or created if not exists
JCachePolicy jcachePolicy = new JCachePolicy();
jcachePolicy.setCacheManager(cacheManager);
jcachePolicy.setCacheName("items")
----------------------------

////
### Find cacheManager
////
### キャッシュマネージャを見つける

////
If _cacheManager_ (and the _cache_) is not set, the policy will try to find a JCache CacheManager object:
////
もし _cacheManager_ （および _cache_）が設定されていない場合、ポリシーは JCache のキャッシュマネージャオブジェクトを見つけようとする:

////
* Lookup a CacheManager in Camel registry - that falls back on JNDI or Spring context based on the environment
* Use the standard api _Caching.getCachingProvider().getCacheManager()_
////
* （環境の JNDI や Spring コンテキストに頼った）Camel レジストリ内のキャッシュマネージャを調べる。
* 標準の API である _Caching.getCachingProvider().getCacheManager()_ を使用する。



[source,java]
----------------------------
//A Cache "getorders" will be used (or created) from the found CacheManager
from("direct:get-orders").routeId("getorders")
    .policy(new JCachePolicy())
    .log("Getting order with id: ${body}")
    .bean(OrderService.class,"findOrderById(${body})");
----------------------------

////
### Partially wrapped route
////
### 部分的にラップされたルート

////
In the examples above the whole route was executed or skipped. A policy can be used to wrap only a segment of the route instead of all processors.
////
以下の例では全体のルートが実行されるかスキップされる。ポリシーは、全プロセッサの代わりにルートのセグメントのみをラップするために使われる。

[source,java]
----------------------------
from("direct:get-orders")
    .log("Order requested: ${body}")
    .policy(new JCachePolicy())
        .log("Getting order with id: ${body}")
        .bean(OrderService.class,"findOrderById(${body})")
    .end()
    .log("Order found: ${body}");
----------------------------

////
The _.log()_ at the beginning and at the end of the route is always called, but the section inside _.policy()_ and _.end()_ is executed based on the cache.
////
ルートの最初と最後にある _.log()_ は常に呼ばれるが、_.policy()_ と _.end()_ 内にあるセクションはキャッシュに基づいて実行される。

////
## KeyExpression
////
## KeyExpression


////
By default the policy uses the received Exchange body as _key_, so the default expression is like _simple("${body})_.
 We can set a different Camel Expression as _keyExpression_ which will be evaluated to determine the key.
 For example if we try to find an _order_ by an _orderId_ which is in the message headers,
 set _header("orderId")_ (or _simple("${header.orderId})_ as _keyExpression_.

The expression is evaluated only once at the beginning of the route to determine the _key_. If nothing was found in cache,
 this _key_ is used to store the _value_ in cache at the end of the route.
////
デフォルトでは、ポリシーは受け取った Exchange のボディを _key_ として使用する。よってデフォルトの expression は _simple("${body})_ のようになる。
キーを決定するために評価される _keyExpression_ として異なる Camel Expression が設定できる。
たとえば、メッセージヘッダ内にある _orderId_ によって _order_ を見つけようとする場合は、_header("orderId")_ （もしくは _simple("${header.orderId}）_ を _keyExpression_ として設定すること。



[source,java]
----------------------------
MutableConfiguration configuration = new MutableConfiguration<>();
configuration.setTypes(String.class, Order.class);
configuration.setExpiryPolicyFactory(CreatedExpiryPolicy.factoryOf(new Duration(TimeUnit.MINUTES, 10)));

JCachePolicy jcachePolicy = new JCachePolicy();
jcachePolicy.setCacheConfiguration(configuration);
jcachePolicy.setCacheName("orders")
jcachePolicy.setKeyExpression(simple("${header.orderId}))

//The cache key is taken from "orderId" header.
from("direct:get-orders")
    .policy(jcachePolicy)
    .log("Getting order with id: ${header.orderId}")
    .bean(OrderService.class,"findOrderById(${header.orderId})");
----------------------------

////
## Camel XML DSL examples
////
## Camel XML DSL の例

////
### Use JCachePolicy in an XML route
////
### Use JCachePolicy in an XML route
XML ルートの中で JCachePolicy を使用する

////
In Camel XML DSL we need a named reference to the JCachePolicy instance (registered in CamelContext or simply in Spring).
 We have to wrap the route between <policy>...</policy> tags after <from>.
////
Camel XML DSL において (Camel コンテキストもしくは Spring で登録されている) JCachePolicy インスタンスへの名前付き参照が必要になる。
<from> タグの後の <policy>...</policy> でルートをラップしなければならない。

[source,xml]
----------------------------
<camelContext xmlns="http://camel.apache.org/schema/spring">
    <route>
        <from uri="direct:get-order"/>
        <policy ref="jCachePolicy" >
            <setBody>
                <method ref="orderService" method="findOrderById(${body})"/>
            </setBody>
        </policy>
    </route>
</camelContext>
----------------------------

////
See this example when only a part of the route is wrapped:
////
ルートの一部がラップされているときのみこの例を参照すること:

[source,xml]
----------------------------
<camelContext xmlns="http://camel.apache.org/schema/spring">
    <route>
        <from uri="direct:get-order"/>
        <log message="Start - This is always called. body:${body}"/>
        <policy ref="jCachePolicy" >
            <log message="Executing route, not found in cache. body:${body}"/>
            <setBody>
                <method ref="orderService" method="findOrderById(${body})"/>
            </setBody>
        </policy>
        <log message="End - This is always called. body:${body}"/>
    </route>
</camelContext>
----------------------------

////
### Define CachePolicy in Spring
////
### Spring におけるキャッシュポリシーを定義する

////
It's more convenient to create a JCachePolicy in Java especially within a RouteBuilder using the Camel DSL expressions,
 but see this example to define it in a Spring XML:
////
Java 特に Camel DSL を用いたルートビルダ内に JCachePolicy を作成すると、より便利である。以下の Spring XML に定義した例を参照のこと:


[source,xml]
----------------------------
<bean id="jCachePolicy" class="org.apache.camel.component.jcache.policy.JCachePolicy">
    <property name="cacheName" value="spring"/>
    <property name="keyExpression">
        <bean class="org.apache.camel.model.language.SimpleExpression">
            <property name="expression" value="${header.mykey}"/>
        </bean>
    </property>
</bean>
----------------------------

////
### Create Cache from XML
////
### XML からキャッシュを生成する

////
It's not strictly speaking related to Camel XML DLS, but JCache providers usually have a way to configure the cache in an XML file.
 For example with Hazelcast you can add a _hazelcast.xml_ to classpath to configure the cache "spring" used in the example above.
////

厳密に Camel XML DSL に関連していないが JCache プロバイダは XML ファイル内でキャッシュを設定する方法を持っている。
たとえば、上記の例において Hazelcast で _hazelcast.xml_ をクラスパスに追加して "spring" キャッシュを設定している。


[source,xml]
----------------------------
<?xml version="1.0" encoding="UTF-8"?>
<hazelcast xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.11.xsd" >

    <cache name="spring">
        <key-type class-name="java.lang.String"/>
        <value-type class-name="java.lang.String"/>
        <expiry-policy-factory>
            <timed-expiry-policy-factory expiry-policy-type="CREATED" duration-amount="60" time-unit="MINUTES"/>
        </expiry-policy-factory>
    </cache>

</hazelcast>
----------------------------


////
=== Special scenarios and error handling
////
=== 特別なシナリオとエラーハンドリング

////
If the Cache used by the policy is closed (can be done dynamically), the whole caching functionality is skipped,
 the route will be executed every time.

If the determined _key_ is _null_, nothing is looked up or stored in cache.

In case of an exception during the route, the error handled is called as always. If the exception gets _handled()_,
 the policy stores the Exchange body, otherwise nothing is added to the cache.
 If an exception happens during evaluating the keyExpression, the routing fails, the error handler is called as normally.
////
ポリシーによるキャッシュが（動的に）閉じられると、全体のキャッシュ機能はスキップされ、毎回ルートが実行される。

もし決定された _key_ が _null_ であれば、何も検索されず、キャッシュに保存もされない。

ルートの途中で例外が発生した場合、エラーハンドルがいつものように呼ばれる。例外が _handled()_ を取得した場合は、ポリシーは Exchange ボディを保存する。それ以外の場合はキャッシュには何も保存されない。
keyExpression を評価している途中に例外が発生した場合は、ルートは失敗し、エラーハンドラは普段通り呼ばれる。
